### PR TITLE
MongoDb storage for openchain server

### PR DESCRIPTION
**Pull request by fluce**
Here is an additionnal storage backend using mongodb for records, transactions and anchorstates.

It uses 3 mongodb collections :
- records : records key, value & version, with denormalized path, type, name
- transactions : transactions, mutations and affected records keys
- anchorstates : ledger anchors

Needed indexes are dynamically created on startup.

I had to force execution environment to dnx451 because dotnetcore is not yet supported for mongodb driver.

### CODE REVIEW

**Comment by Flavien** [comment]
Thanks a lot @fluce for writing this code.

I reviewed it and have a few comments:

- The main blocking issue is the lack of ACID semantics for MongoDB: In ``MongoDbStorageEngine.AddTransactions``, it's possible for the ``Record`` collection to be updated without the ``Transaction`` collection being updated if something fails in between both updates. This will break the assumptions required by Openchain.
- There should be unit tests. In particular the ``BaseStorageEngineTests`` and ``BaseLedgerTests`` test classes contain tests that any storage engine should pass.
- User secrets are already handled by the ``AddUserSecrets`` call. On Windows, the file should be stored in ``Users\Flavien\AppData\Roaming\Microsoft\UserSecrets\Openchain.Server\secrets.json``. The [API is cross platform](https://github.com/aspnet/UserSecrets) and will store secrets encrypted in the future.

I think it would be better to create a separate dedicated repository under the Openchain organization (like https://github.com/Openchain/openchain-mongodb) and give you push rights on it. The idea behind the component model introduced recently is that end-users can pull a third-party storage engine through NuGet by modifying the dependencies in ``project.json``, then ``dnu restore``. In your repository, you can simply reference the core Openchain packages through NuGet. Does that work for you?

**Comment by fluce** [comment]
@Flavien,

I added a record write lock and a pending transaction collection to deal with most of ACID concerns.

Records affected by a transaction are locked using transaction hash, current values are recorded in a pending transaction collection.

After records are updated and transaction is inserted, locks and pending transaction are removed.

If an exception occured, data stored in the pending transaction are used to reset the records to their previous states.

If the thread (or process) is interrupted (without exception), a worker thread deals with the orphaned transaction and rolls it back. 

When reading records, lock presence is tested and the read spins until the lock is removed or a timeout occurred.

Next to do :
* Test locks for other kinds read accesses
* Filter transactions in GetLastTransaction and GetTransactions to stop enumerating transaction if a pending transaction is found

Concerning unit tests, I will add minimal tests but they won't be self contained and will need a mongodb instance.

I knew the user secrets feature, but I choose the simplest way, partly because I use the secret file more as a 'local' settings store than as a 'secret' one. I will look into it deeper.

I think it's a good idea to isolate the mongodb storage provider in it's own repository. But for this to work I will need the dependency resolver patch to be merged, or any other way to support a net451 only provider. Let me know if it's possible.

**Comment by Flavien** [comment]
Hi @fluce,

That sounds good.

An option I was thinking about to avoid having to use a background worker is to use the following steps when a transaction is submitted:

1. Cleanup any pending transaction (see below).
2. Insert the new transaction as pending.
3. Apply the changes to the Records collection.
4. Update the transaction as complete.

Then step 1 (Cleanup any pending transaction) would be:

1. Start at the first pending transaction.
2. Apply the changes to the Record collection.
3. Update the transaction as complete.
4. Move to the next transaction and return to 2 until there is no more pending transaction.

But I am sure there are edge conditions I am not thinking about.

I created the [openchain/mongodb-storage repository](https://github.com/openchain/mongodb-storage) to host the code you are writing, and you should have push rights on it.

Regarding the ability to use your package with Openchain, you can have a look at [this](https://github.com/openchain/run). The [project.json](https://github.com/openchain/run/blob/master/project.json) file will make sure the Openchain server package is pulled and run as the entry point.

You just need to add yours to the list of dependencies, and remove ``dnxcore50`` from the list of frameworks to make sure dnx doesn't complain.

**Comment by fluce** [comment]
@Flavien,

I've just committed a first version of MongoDb-Storage provider.

I kept the background worker around for now. In practice, it should only works at startup to recover from a unexpected shutdown. I need to prepare a kind of load test to verify the whole commit system works well with a heavy activity.

I don't think the recovery process should try to complete the transaction, because the client application has received an error implying the transaction submission has gone wrong. So, the recovery process should rollback it properly. It's how the Sqlite provider works with the transaction scope.

I had a few problems to use my project and the other modules sources in a development environment: dnu restore still has a few mysteries for me... At a time the module compiles correctly in VS, but intellisense was completly lost and I had hundreds of errors in the editor...

How do you manage multiple repository/solution in your development setup ?

Fred

**Comment by Flavien** [comment]
You should add the Openchain repository as a submodule to your repository, then reference the projects from the solution.

See how I did it on a fork of your repository: https://github.com/Flavien/mongodb-storage (feel free to merge my changes).

You might have some problems with the unit tests because right now, the XUnit unit tests runner only works with .NET Core.

**Comment by fluce** [comment]
Works well !

Even with unit tests, which runs correctly one I added dnx451 in project.json for Infrastructure.tests and Abstractions.tests. I also had to reimplement Task.FromException (not available with dnx451) in file  test/Openchain.Infrastructure.Tests/PollingObservableTests.cs (check https://github.com/fluce/openchain/commit/3afe7b17368aa51ba2d97a9a483731e7486d1ea2).

One question about something else : why don't you exclude project.lock.json from source control ? It's recalculated by dnu restore anyway, and it pollutes commits details (except of course if you set "locked"=true in the file, but it's not the case).

**Comment by Flavien** [comment]
Glad to know it works.

I will make sure to target dnx452 in the unit tests projects (dnx452 has FromException).

Good point with the lock files. I think I will exclude them from source control.

I will now close this PR as it's no longer relevant, but to keep the discussion going, feel free to open an issue either on this repository or on mongodb-storage and tag me so I get a notification.

**Comment by Flavien** [comment]
I've pushed those changes. You should be able to update the submodule, the unit test projects are now targetting dnx452.

Also, the lock files are now ignored.

**Comment by karneaud** [comment]
Doesn't work

**Pull request closed without merging**
